from __future__ import annotations

import csv
import random
from datetime import datetime, timedelta
from pathlib import Path


TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

SUPPORTED_TIMESTAMP_FORMATS = [
    "%Y-%m-%d %H:%M:%S",
    "%d-%m-%Y %H:%M",
]


def parse_datetime(value: str) -> datetime:
    """Parse timestamps generated by the simulator."""

    for timestamp_format in SUPPORTED_TIMESTAMP_FORMATS:
        try:
            return datetime.strptime(value, timestamp_format)
        except ValueError:
            continue

    raise ValueError(
        f"Unsupported timestamp format: {value!r}"
    )


def format_datetime(value: datetime) -> str:
    return value.strftime(TIMESTAMP_FORMAT)


def load_csv(filename: str) -> list[dict]:
    """Load a simulator dataset from src/datasets."""
    dataset_dir = Path(__file__).parent.parent / "datasets"
    input_file = dataset_dir / filename

    if not input_file.exists():
        raise FileNotFoundError(
            f"Required dataset not found: {input_file}"
        )

    with input_file.open(
        "r",
        newline="",
        encoding="utf-8",
    ) as file:
        return list(csv.DictReader(file))


def generate_operational_events(
    orders: list[dict],
    fulfilment_units: list[dict],
    deliveries: list[dict],
    assignments: list[dict],
) -> tuple[
    list[dict],
    list[dict],
    list[dict],
]:
    """
    Generate a coherent operational timeline.

    Returns:
        events
        updated fulfilment units
        updated deliveries
    """

    orders_by_id = {
        order["order_id"]: order
        for order in orders
    }

    deliveries_by_fulfilment = {
        delivery["fulfilment_unit_id"]: delivery
        for delivery in deliveries
    }

    assignments_by_delivery: dict[str, list[dict]] = {}

    for assignment in assignments:
        assignments_by_delivery.setdefault(
            assignment["delivery_id"],
            [],
        ).append(assignment)

    events: list[dict] = []
    updated_fulfilments: list[dict] = []
    updated_deliveries: list[dict] = []

    event_counter = 1

    def add_event(
        event_type: str,
        occurred_at: datetime,
        order_id: str | None = None,
        fulfilment_unit_id: str | None = None,
        delivery_id: str | None = None,
        store_id: str | None = None,
        rider_id: str | None = None,
        reason: str | None = None,
    ) -> None:
        nonlocal event_counter

        events.append(
            {
                "event_id": f"EVT-{event_counter:07d}",
                "event_type": event_type,
                "occurred_at": format_datetime(occurred_at),
                "order_id": order_id or "",
                "fulfilment_unit_id": (
                    fulfilment_unit_id or ""
                ),
                "delivery_id": delivery_id or "",
                "store_id": store_id or "",
                "rider_id": rider_id or "",
                "reason": reason or "",
            }
        )

        event_counter += 1

    for fulfilment in fulfilment_units:
        fulfilment = dict(fulfilment)

        order_id = fulfilment["order_id"]
        fulfilment_unit_id = fulfilment[
            "fulfilment_unit_id"
        ]
        store_id = fulfilment["store_id"]

        order = orders_by_id.get(order_id)

        if order is None:
            raise ValueError(
                f"Order not found: {order_id}"
            )

        assigned_to_store_at = parse_datetime(
            fulfilment["assigned_to_store_at"]
        )

        order_created_at = parse_datetime(
            order["created_at"]
        )

        payment_success_at = parse_datetime(
            order["payment_success_at"]
        )

        # Basic order-level events are generated once for each
        # fulfilment's parent order. Duplicate prevention is handled
        # below with a set.
        #
        # We need to ensure the order-created/payment events are not
        # duplicated for split fulfilments.
        if not any(
            event["event_type"] == "ORDER_CREATED"
            and event["order_id"] == order_id
            for event in events
        ):
            add_event(
                event_type="ORDER_CREATED",
                occurred_at=order_created_at,
                order_id=order_id,
            )

            add_event(
                event_type="PAYMENT_SUCCESS",
                occurred_at=payment_success_at,
                order_id=order_id,
            )

        # Cancelled and failed fulfilments do not continue through
        # the normal picking/packing/delivery lifecycle.
        if fulfilment["status"] == "CANCELLED":
            cancellation_time = (
                parse_datetime(fulfilment["cancelled_at"])
                if fulfilment["cancelled_at"]
                else assigned_to_store_at
                + timedelta(minutes=2)
            )

            add_event(
                event_type="STORE_ASSIGNED",
                occurred_at=assigned_to_store_at,
                order_id=order_id,
                fulfilment_unit_id=fulfilment_unit_id,
                store_id=store_id,
            )

            add_event(
                event_type="FULFILMENT_CANCELLED",
                occurred_at=cancellation_time,
                order_id=order_id,
                fulfilment_unit_id=fulfilment_unit_id,
                store_id=store_id,
                reason=fulfilment[
                    "cancellation_reason"
                ],
            )

            fulfilment["cancelled_at"] = format_datetime(
                cancellation_time
            )

            updated_fulfilments.append(fulfilment)
            continue

        if fulfilment["status"] == "FAILED":
            failure_time = (
                parse_datetime(fulfilment["failed_at"])
                if fulfilment["failed_at"]
                else assigned_to_store_at
                + timedelta(minutes=2)
            )

            add_event(
                event_type="STORE_ASSIGNED",
                occurred_at=assigned_to_store_at,
                order_id=order_id,
                fulfilment_unit_id=fulfilment_unit_id,
                store_id=store_id,
            )

            add_event(
                event_type="FULFILMENT_FAILED",
                occurred_at=failure_time,
                order_id=order_id,
                fulfilment_unit_id=fulfilment_unit_id,
                store_id=store_id,
                reason=fulfilment["failure_reason"],
            )

            fulfilment["failed_at"] = format_datetime(
                failure_time
            )

            updated_fulfilments.append(fulfilment)
            continue

        # -----------------------------
        # Normal fulfilment lifecycle
        # -----------------------------

        picking_started_at = (
            assigned_to_store_at
            + timedelta(
                seconds=random.randint(60, 180)
            )
        )

        picking_duration = timedelta(
            minutes=random.randint(2, 7),
            seconds=random.randint(0, 59),
        )

        picking_completed_at = (
            picking_started_at
            + picking_duration
        )

        packing_started_at = (
            picking_completed_at
            + timedelta(
                seconds=random.randint(15, 45)
            )
        )

        packing_duration = timedelta(
            minutes=random.randint(1, 3),
            seconds=random.randint(0, 30),
        )

        packing_completed_at = (
            packing_started_at
            + packing_duration
        )

        add_event(
            event_type="STORE_ASSIGNED",
            occurred_at=assigned_to_store_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            store_id=store_id,
        )

        add_event(
            event_type="PICKING_STARTED",
            occurred_at=picking_started_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            store_id=store_id,
        )

        add_event(
            event_type="PICKING_COMPLETED",
            occurred_at=picking_completed_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            store_id=store_id,
        )

        add_event(
            event_type="PACKING_STARTED",
            occurred_at=packing_started_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            store_id=store_id,
        )

        add_event(
            event_type="PACKING_COMPLETED",
            occurred_at=packing_completed_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            store_id=store_id,
        )

        fulfilment["picking_started_at"] = (
            format_datetime(picking_started_at)
        )

        fulfilment["picking_completed_at"] = (
            format_datetime(picking_completed_at)
        )

        fulfilment["packing_started_at"] = (
            format_datetime(packing_started_at)
        )

        fulfilment["packing_completed_at"] = (
            format_datetime(packing_completed_at)
        )

        delivery = deliveries_by_fulfilment.get(
            fulfilment_unit_id
        )

        if delivery is None:
            fulfilment["completed_at"] = (
                format_datetime(packing_completed_at)
            )

            updated_fulfilments.append(fulfilment)
            continue

        delivery = dict(delivery)

        delivery_id = delivery["delivery_id"]

        delivery_assignments = assignments_by_delivery.get(
            delivery_id,
            [],
        )

        accepted_assignment = next(
            (
                assignment
                for assignment in delivery_assignments
                if assignment["response"] == "ACCEPTED"
            ),
            None,
        )

        if accepted_assignment is None:
            delivery["status"] = "NO_RIDER_ACCEPTED"

            updated_deliveries.append(delivery)

            fulfilment["completed_at"] = ""

            updated_fulfilments.append(fulfilment)
            continue

        rider_id = accepted_assignment["rider_id"]
        rider_assigned_at = parse_datetime(
            accepted_assignment["responded_at"]
        )

        rider_arrived_at_store = (
            rider_assigned_at
            + timedelta(
                minutes=random.randint(1, 5)
            )
        )

        picked_up_at = (
            max(
                rider_arrived_at_store,
                packing_completed_at,
            )
            + timedelta(
                seconds=random.randint(15, 60)
            )
        )

        delivery_started_at = (
            picked_up_at
            + timedelta(
                seconds=random.randint(15, 90)
            )
        )

        # Traffic and weather influence transit duration.
        base_transit_minutes = random.uniform(3, 9)

        if delivery["traffic_condition"] == "HIGH":
            base_transit_minutes += random.uniform(
                2,
                5,
            )
        elif delivery["traffic_condition"] == "SEVERE":
            base_transit_minutes += random.uniform(
                5,
                10,
            )

        if delivery["weather_condition"] == "RAIN":
            base_transit_minutes += random.uniform(
                1,
                4,
            )

        delivered_at = (
            delivery_started_at
            + timedelta(
                minutes=base_transit_minutes
            )
        )

        add_event(
            event_type="RIDER_ASSIGNED",
            occurred_at=rider_assigned_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            delivery_id=delivery_id,
            store_id=store_id,
            rider_id=rider_id,
        )

        add_event(
            event_type="RIDER_ARRIVED_AT_STORE",
            occurred_at=rider_arrived_at_store,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            delivery_id=delivery_id,
            store_id=store_id,
            rider_id=rider_id,
        )

        add_event(
            event_type="PICKED_UP",
            occurred_at=picked_up_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            delivery_id=delivery_id,
            store_id=store_id,
            rider_id=rider_id,
        )

        add_event(
            event_type="DELIVERY_STARTED",
            occurred_at=delivery_started_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            delivery_id=delivery_id,
            store_id=store_id,
            rider_id=rider_id,
        )

        add_event(
            event_type="DELIVERED",
            occurred_at=delivered_at,
            order_id=order_id,
            fulfilment_unit_id=fulfilment_unit_id,
            delivery_id=delivery_id,
            store_id=store_id,
            rider_id=rider_id,
        )

        delivery["rider_id"] = rider_id
        delivery["status"] = "DELIVERED"
        delivery["rider_arrived_at_store"] = (
            format_datetime(rider_arrived_at_store)
        )
        delivery["picked_up_at"] = (
            format_datetime(picked_up_at)
        )
        delivery["delivery_started_at"] = (
            format_datetime(delivery_started_at)
        )
        delivery["delivered_at"] = (
            format_datetime(delivered_at)
        )

        fulfilment["completed_at"] = (
            format_datetime(delivered_at)
        )

        updated_deliveries.append(delivery)
        updated_fulfilments.append(fulfilment)

    # Sort events globally by time.
    events.sort(
        key=lambda event: event["occurred_at"]
    )

    return (
        events,
        updated_fulfilments,
        updated_deliveries,
    )


def save_events(events: list[dict]) -> None:
    output_dir = Path(__file__).parent.parent / "datasets"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "operational_events.csv"

    fieldnames = [
        "event_id",
        "event_type",
        "occurred_at",
        "order_id",
        "fulfilment_unit_id",
        "delivery_id",
        "store_id",
        "rider_id",
        "reason",
    ]

    with output_file.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(events)

    print(f"Generated {len(events)} operational events")
    print(f"Dataset saved to: {output_file}")


def save_fulfilment_units(
    fulfilment_units: list[dict],
) -> None:
    output_dir = Path(__file__).parent.parent / "datasets"
    output_file = output_dir / "fulfilment_units.csv"

    fieldnames = [
        "fulfilment_unit_id",
        "order_id",
        "store_id",
        "status",
        "assigned_to_store_at",
        "picking_started_at",
        "picking_completed_at",
        "packing_started_at",
        "packing_completed_at",
        "cancelled_at",
        "cancellation_reason",
        "failed_at",
        "failure_reason",
        "completed_at",
    ]

    with output_file.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(fulfilment_units)


def save_deliveries(
    deliveries: list[dict],
) -> None:
    output_dir = Path(__file__).parent.parent / "datasets"
    output_file = output_dir / "deliveries.csv"

    fieldnames = [
        "delivery_id",
        "fulfilment_unit_id",
        "rider_id",
        "status",
        "rider_arrived_at_store",
        "picked_up_at",
        "delivery_started_at",
        "delivered_at",
        "delivery_distance",
        "traffic_condition",
        "weather_condition",
        "cancelled_at",
        "cancellation_reason",
        "failed_at",
        "failure_reason",
    ]

    with output_file.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(deliveries)


if __name__ == "__main__":
    orders = load_csv("orders.csv")
    fulfilment_units = load_csv(
        "fulfilment_units.csv"
    )
    deliveries = load_csv("deliveries.csv")
    assignments = load_csv(
        "rider_assignments.csv"
    )

    (
        events,
        updated_fulfilments,
        updated_deliveries,
    ) = generate_operational_events(
        orders=orders,
        fulfilment_units=fulfilment_units,
        deliveries=deliveries,
        assignments=assignments,
    )

    save_events(events)

    save_fulfilment_units(
        updated_fulfilments
    )

    save_deliveries(
        updated_deliveries
    )